### ISSUE TITLE
Não consigo executar na versão 4.30

### ISSUE THREAD

**Issue by ptinchant** [nopCommerceBrasil/NopBrasil.Plugin.Payments.PagSeguro#9]
Poderiam por favor me ajudar a realizar a instalação do plugin na versao 4.30 do nopCommerce?

**Comment by almirrps** [comment]
> Poderiam por me ajudar a ajudar a realizar a instalação do plugin na versão 4.30 do nopCommerce?
@ptinchant eu também estou precisando deste plugin na versão 4.30. Tive o mesmo problema com o plugin dos correios, mas tive a ajuda de alguns programadores que atualizaram na mão para a versão 4.30 do NopCommerce.
Vou dar uma sapiada neste plugin e se conseguir atualizar ele eu disponibilizo aqui - tá OK?
Acho que não vamos conseguir um retorno do pessoal que mantém este plugin, teremos que nos virar mesmo...

**Comment by almirrps** [comment]
@ptinchant consegui atualizar para a versão 4.30, só que não tenho autorização pra subir aqui no Git do NopCommerce Brasil. Tem interesse? Se quiser te passo por email ou algum link de download.

**Comment by ptinchant** [comment]
@almirrps tenho interesse sim, se puder me passar eu agradeço...
o dos correios, eu consegui fazer funcionar alterando um campo na configuração dele

**Comment by ricardodefernandes** [comment]
@almirrps pode me enviar a versão 4.30? Desde já agradeço.

**Comment by almirrps** [comment]
Opa! Segue o git abaixo senhores. Pelo menos ontem eu instalei, configurei e ativei normalmente, hoje vou começar os testes para ver se está funcionando 100%. Se identificarem algum problema me informem e vamos atualizando aqui, depois que o pessoal do NopBrasil autorizar a gente joga pro repositório deles.
https://github.com/almirrps/nopbrasil.plugin.payments.pagseguro

Falow

**Comment by almirrps** [comment]
Fazendo os testes aqui, está retornando o seguinte erro no log do sistema quando tenta ser redirecionado:
HttpStatusCode: BadRequest
Mensagem completa	
Uol.PagSeguro.PagSeguroServiceException: HttpStatusCode: BadRequest
   at Uol.PagSeguro.PaymentService.RegisterCore(Credentials credentials, PaymentRequest payment)
   at Uol.PagSeguro.PaymentService.Register(Credentials credentials, PaymentRequest payment)
   at NopBrasil.Plugin.Payments.PagSeguro.Services.PagSeguroService.CreatePayment(PostProcessPaymentRequest postProcessPaymentRequest)
   at NopBrasil.Plugin.Payments.PagSeguro.PagSeguroPaymentProcessor.PostProcessPayment(PostProcessPaymentRequest postProcessPaymentRequest)
11213=Malformed request: Content is not allowed in prolog.. 


Vou dar uma olhada para ver o que é, mas se conseguirem identificar já vão passando - tá OK?

**Comment by lelemm** [comment]
@almirrps , ainda tem esse cara ai? consegue passar por favor? :)
